version: '3.8'

services:
    postgres:
        image: postgres:13.0-alpine
        volumes:
            - postgres_db:/var/lib/postgresql/data/
        env_file:
            - ./.env

    app:
        image: andpigge/api_yamdb:latest
        restart: always
        volumes:
            - static_value:/app/static/
            - media_value:/app/media/
        depends_on:
            - postgres
        env_file:
            - ./.env

    nginx:
        image: nginx:1.21.3-alpine
        ports:
            - "3000:3000"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_value:/var/html/static/
            - media_value:/var/html/media/
        depends_on:
            - app

volumes:
    static_value:
    media_value:
    postgres_db:
